apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres-haccp
    type: postgres
    access: proxy
    url: postgres:5432
    database: rag_monitoring
    user: raguser
    secureJsonData:
      password: ragpassword
    jsonData:
      database: rag_monitoring
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false
